//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anu.PunishmentOrg.Resources.Common {

    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_ResultType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ResultType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anu.PunishmentOrg.Resources.Anu.PunishmentOrg.Resources.Common.Resources.ResultTy" +
                            "pe", typeof(Resources_ResultType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای غیر منتظره.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیتی برای صورتجلسه کشف ارسالی یافت نشد..
        /// </summary>
        public static string Error_to_Find_State {
            get {
                return ResourceManager.GetString("Error_to_Find_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره یکتای صورتجلسه کشف درخواستی الزامی میباشد..
        /// </summary>
        public static string Error_UniqueNo_Is_Required {
            get {
                return ResourceManager.GetString("Error_UniqueNo_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به واحد اجرای احکام ارجاع شده.
        /// </summary>
        public static string Execution {
            get {
                return ResourceManager.GetString("Execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره قبض تکراری است و امروز قابل ثبت نیست.
        /// </summary>
        public static string PBillStore_Duplicate_Bill {
            get {
                return ResourceManager.GetString("PBillStore_Duplicate_Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست کالا خالی است!.
        /// </summary>
        public static string PBillStore_NoProductListProvided {
            get {
                return ResourceManager.GetString("PBillStore_NoProductListProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت و ارسال به مرجع رسیدگی کننده.
        /// </summary>
        public static string PDiscoveryMinuteSate_ConfirmAndSendToUnit {
            get {
                return ResourceManager.GetString("PDiscoveryMinuteSate_ConfirmAndSendToUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تشکیل پرونده شده است..
        /// </summary>
        public static string PDiscoveryMinuteSate_CreateCase {
            get {
                return ResourceManager.GetString("PDiscoveryMinuteSate_CreateCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت نسخه فیزیکی صورتجلسه کشف قبل از نسخه الکترونیکی.
        /// </summary>
        public static string PDiscoveryMinuteSate_Expired {
            get {
                return ResourceManager.GetString("PDiscoveryMinuteSate_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره یکتای صورتجلسه کشف ارسالی معتبر نمی باشد.
        /// </summary>
        public static string PDiscoveryMinuteSate_No_Is_NotValid {
            get {
                return ResourceManager.GetString("PDiscoveryMinuteSate_No_Is_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورتجلسه كشف / گزارش كشف اسنادي ثبت موقت شده.
        /// </summary>
        public static string PDiscoveryMinuteSate_PrimRegistery {
            get {
                return ResourceManager.GetString("PDiscoveryMinuteSate_PrimRegistery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال شده به شهر دیگر به دلیل اشتباه در ارجاع.
        /// </summary>
        public static string PDiscoveryMinuteSate_ReferToCity {
            get {
                return ResourceManager.GetString("PDiscoveryMinuteSate_ReferToCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارجاع شده به شعبه رسیدگی کننده.
        /// </summary>
        public static string PDiscoveryMinuteSate_ReferToUnit {
            get {
                return ResourceManager.GetString("PDiscoveryMinuteSate_ReferToUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورتجلسه کشف ارسال شده به سامانه قاچاق.
        /// </summary>
        public static string PDiscoveryMinuteSate_SendToSmuggling {
            get {
                return ResourceManager.GetString("PDiscoveryMinuteSate_SendToSmuggling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع شده.
        /// </summary>
        public static string PDiscoveryMinuteSate_Start {
            get {
                return ResourceManager.GetString("PDiscoveryMinuteSate_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رای صادر شده است..
        /// </summary>
        public static string PJudgment {
            get {
                return ResourceManager.GetString("PJudgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد ..
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مکان جغرافیایی گزارش بازرسی نمی تواند خالی باشد.
        /// </summary>
        public static string ThePBBillGeoLocation_Is_Required {
            get {
                return ResourceManager.GetString("ThePBBillGeoLocation_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری و کلمه عبور را وارد کنید.
        /// </summary>
        public static string UserName_Or_PassWord_Is_Not_Entered {
            get {
                return ResourceManager.GetString("UserName_Or_PassWord_Is_Not_Entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با نام کاربری و کلمه عبور ارسالی هیچ دسترسی برای سرویس جاری یافت نشد.
        /// </summary>
        public static string UserName_Or_PassWord_Is_Not_Valid {
            get {
                return ResourceManager.GetString("UserName_Or_PassWord_Is_Not_Valid", resourceCulture);
            }
        }
    }
}
