//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anu.PunishmentOrg.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_ResultType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ResultType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anu.PunishmentOrg.Resources.Common.Resources.ResultType", typeof(Resources_ResultType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تاریخ تولد خود را وارد نمایید.
        /// </summary>
        public static string BirthDate_Is_Not_Entered {
            get {
                return ResourceManager.GetString("BirthDate_Is_Not_Entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد معتبر نمی باشد.
        /// </summary>
        public static string BirthDate_Is_Not_Valid {
            get {
                return ResourceManager.GetString("BirthDate_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکلی در سیستم بابت دسترسی ها بوجود آمده است لطفا با پشتیبانی تماس حاصل فرمایید..
        /// </summary>
        public static string Can_Not_Find_AccessType {
            get {
                return ResourceManager.GetString("Can_Not_Find_AccessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای غیر منتظره.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیتی برای {0} ارسالی یافت نشد..
        /// </summary>
        public static string Error_to_Find_State {
            get {
                return ResourceManager.GetString("Error_to_Find_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره {0} درخواستی الزامی میباشد..
        /// </summary>
        public static string Error_UniqueNo_Is_Required {
            get {
                return ResourceManager.GetString("Error_UniqueNo_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به واحد اجرای احکام ارجاع شده.
        /// </summary>
        public static string Execution {
            get {
                return ResourceManager.GetString("Execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام خود را وارد نمایید.
        /// </summary>
        public static string FirstName_Is_Not_Entered {
            get {
                return ResourceManager.GetString("FirstName_Is_Not_Entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست بدنه نمی‌تواند خالی باشد..
        /// </summary>
        public static string GeoLocation_Request_IsNull {
            get {
                return ResourceManager.GetString("GeoLocation_Request_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلدهای ضروری پر نشده است.
        /// </summary>
        public static string GeoLocation_Request_NotValid {
            get {
                return ResourceManager.GetString("GeoLocation_Request_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست ورودی خالی یا نا معتبر میباشد.
        /// </summary>
        public static string In_Valid_Input {
            get {
                return ResourceManager.GetString("In_Valid_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای استفاده از خدمت نیاز به ورود دارید..
        /// </summary>
        public static string JwtTokenIsNotValid {
            get {
                return ResourceManager.GetString("JwtTokenIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام خوانوادگی خود را وارد نمایید.
        /// </summary>
        public static string LastName_Is_Not_Entered {
            get {
                return ResourceManager.GetString("LastName_Is_Not_Entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مجددا وارد شوید.
        /// </summary>
        public static string Login_Again {
            get {
                return ResourceManager.GetString("Login_Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد عبور برای شماره {0} ارسال شد ..
        /// </summary>
        public static string LoginSuccessful_Sms_Send_To {
            get {
                return ResourceManager.GetString("LoginSuccessful_Sms_Send_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد واحد پرونده نامرتبط است..
        /// </summary>
        public static string MechanizedLetter_CaseHandlerUnitId_Is_Not_Sync_UnitId {
            get {
                return ResourceManager.GetString("MechanizedLetter_CaseHandlerUnitId_Is_Not_Sync_UnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پرونده نامعتبر است..
        /// </summary>
        public static string MechanizedLetter_CaseNo_Is_Not_Valid {
            get {
                return ResourceManager.GetString("MechanizedLetter_CaseNo_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پرونده را وارد نمایید..
        /// </summary>
        public static string MechanizedLetter_CaseNo_Is_Null {
            get {
                return ResourceManager.GetString("MechanizedLetter_CaseNo_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد واحد پرونده نامعتبر است.
        /// </summary>
        public static string MechanizedLetter_CaseUnit_Is_Not_Valid {
            get {
                return ResourceManager.GetString("MechanizedLetter_CaseUnit_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد واحد پرونده را وارد نمایید..
        /// </summary>
        public static string MechanizedLetter_CaseUnit_Is_Null {
            get {
                return ResourceManager.GetString("MechanizedLetter_CaseUnit_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كاربر ثبت كننده نامه را وارد کنید..
        /// </summary>
        public static string MechanizedLetter_CreatorUserName_Is_Null {
            get {
                return ResourceManager.GetString("MechanizedLetter_CreatorUserName_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد موضوع نامه نامعتبر است..
        /// </summary>
        public static string MechanizedLetter_GMechanizedLetterTypeCode_Is_Not_Valid {
            get {
                return ResourceManager.GetString("MechanizedLetter_GMechanizedLetterTypeCode_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد نوع موضوع نامه را انتخاب کنید..
        /// </summary>
        public static string MechanizedLetter_GMechanizedLetterTypeCode_Is_null {
            get {
                return ResourceManager.GetString("MechanizedLetter_GMechanizedLetterTypeCode_Is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن نامه را وارد نمایید..
        /// </summary>
        public static string MechanizedLetter_LetterText_Is_Null {
            get {
                return ResourceManager.GetString("MechanizedLetter_LetterText_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار نوع گيرنده از نطر گيرنده اصل نامه/رونوشت گيرنده معتبر نمی باشد..
        /// </summary>
        public static string MechanizedLetter_mainRcvOrTranscriptRcv_Is_Not_Valid {
            get {
                return ResourceManager.GetString("MechanizedLetter_mainRcvOrTranscriptRcv_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع گيرنده از نطر گيرنده اصل نامه/رونوشت گيرنده را وارد نمایید..
        /// </summary>
        public static string MechanizedLetter_mainRcvOrTranscriptRcv_Is_Null {
            get {
                return ResourceManager.GetString("MechanizedLetter_mainRcvOrTranscriptRcv_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن کد واحد فرستنده نامه اجباری می باشد..
        /// </summary>
        public static string MechanizedLetter_NAJAUnit_Is_Null {
            get {
                return ResourceManager.GetString("MechanizedLetter_NAJAUnit_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ نامه فرستنده معتبر نمی باشد..
        /// </summary>
        public static string MechanizedLetter_OuterOrgLetterDate_Is_Not_ValidDate {
            get {
                return ResourceManager.GetString("MechanizedLetter_OuterOrgLetterDate_Is_Not_ValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ نامه فرستنده را وارد نمایید...
        /// </summary>
        public static string MechanizedLetter_OuterOrgLetterDate_Is_Null {
            get {
                return ResourceManager.GetString("MechanizedLetter_OuterOrgLetterDate_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره نامه فرستنده از نوع عدد نمی باشد..
        /// </summary>
        public static string MechanizedLetter_OuterOrgLetterNo_Is_Not_Digit {
            get {
                return ResourceManager.GetString("MechanizedLetter_OuterOrgLetterNo_Is_Not_Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره نامه فرستنده را وارد نمایید..
        /// </summary>
        public static string MechanizedLetter_OuterOrgLetterNo_Is_Null {
            get {
                return ResourceManager.GetString("MechanizedLetter_OuterOrgLetterNo_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار نوع گيرنده نامه/رونوشت از نظر واحدي/سمتي/کاربري نامعتبر است..
        /// </summary>
        public static string MechanizedLetter_ReceiverType_Is_Not_Valid {
            get {
                return ResourceManager.GetString("MechanizedLetter_ReceiverType_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع گيرنده نامه/رونوشت از نظر واحدي/سمتي/کاربري را وارد نمایید..
        /// </summary>
        public static string MechanizedLetter_ReceiverType_Is_Null {
            get {
                return ResourceManager.GetString("MechanizedLetter_ReceiverType_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن اطلاعات حداقل یک گیرنده برای نامه اجباری می باشد..
        /// </summary>
        public static string MechanizedLetter_RecieveGMechanizedLetterServiceResult_Reciver_Is_Null {
            get {
                return ResourceManager.GetString("MechanizedLetter_RecieveGMechanizedLetterServiceResult_Reciver_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار نوع نامه از نظر نامه بازگشتي یا پيروي نامعتبر است..
        /// </summary>
        public static string MechanizedLetter_RelLetters_relationType_Is_Not_Valid {
            get {
                return ResourceManager.GetString("MechanizedLetter_RelLetters_relationType_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع نامه از نظر نامه بازگشتي یا پيروي را وارد کنید..
        /// </summary>
        public static string MechanizedLetter_RelLetters_relationType_Is_Null {
            get {
                return ResourceManager.GetString("MechanizedLetter_RelLetters_relationType_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع نامه از نظر مکانيزه بودن يا غيرمکانيزه بودن نامه بازگشتي یا پيروي نامعتبر است..
        /// </summary>
        public static string MechanizedLetter_RelLetters_RelLetterGetType_Is_Not_Valid {
            get {
                return ResourceManager.GetString("MechanizedLetter_RelLetters_RelLetterGetType_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع نامه از نظر مکانيزه بودن يا غيرمکانيزه بودن نامه بازگشتي یا پيروي را وارد کنید..
        /// </summary>
        public static string MechanizedLetter_RelLetters_RelLetterGetType_Is_Null {
            get {
                return ResourceManager.GetString("MechanizedLetter_RelLetters_RelLetterGetType_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره نامه بازگشتي یا پيروي نامعتبر است..
        /// </summary>
        public static string MechanizedLetter_RelLetters_RelLetterNo_Is_Not_Valid {
            get {
                return ResourceManager.GetString("MechanizedLetter_RelLetters_RelLetterNo_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره نامه بازگشتي یا پيروي را وارد نمایید..
        /// </summary>
        public static string MechanizedLetter_RelLetters_RelLetterNo_Is_Null {
            get {
                return ResourceManager.GetString("MechanizedLetter_RelLetters_RelLetterNo_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن پارامترهای ورودی اجباری می باشد..
        /// </summary>
        public static string MechanizedLetter_Request_Is_Null {
            get {
                return ResourceManager.GetString("MechanizedLetter_Request_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد واحد فرستنده نامه معتبر نمی باشد..
        /// </summary>
        public static string MechanizedLetter_SenderOuterOrgCode_Is_Not_Valid {
            get {
                return ResourceManager.GetString("MechanizedLetter_SenderOuterOrgCode_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد واحد فرستنده نامه را وارد نمایید..
        /// </summary>
        public static string MechanizedLetter_SenderOuterOrgCode_Is_Null {
            get {
                return ResourceManager.GetString("MechanizedLetter_SenderOuterOrgCode_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد واحد گیرنده نامه معتبر نمی باشد..
        /// </summary>
        public static string MechanizedLetter_TheReceiverInnerOrgCode_Is_Not_Valid {
            get {
                return ResourceManager.GetString("MechanizedLetter_TheReceiverInnerOrgCode_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد پرونده را مقدار دهی نمایید..
        /// </summary>
        public static string MechanizedLetter_TheUnit_Is_Null {
            get {
                return ResourceManager.GetString("MechanizedLetter_TheUnit_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا کد ملی را وارد نمایید..
        /// </summary>
        public static string NationalCode_Is_Not_Entered {
            get {
                return ResourceManager.GetString("NationalCode_Is_Not_Entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا کد ملی را صحیح وارد نمایید..
        /// </summary>
        public static string NationalCode_Is_Not_Valid {
            get {
                return ResourceManager.GetString("NationalCode_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول کد ملی باید ده کاراکتر باشد..
        /// </summary>
        public static string NationalCode_Length_Is_Not_Valid {
            get {
                return ResourceManager.GetString("NationalCode_Length_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی تشکیل شده از ده رقم عددی می‌باشد؛ لطفا کد ملی را صحیح وارد نمایید..
        /// </summary>
        public static string NationalCode_Must_Be_Number {
            get {
                return ResourceManager.GetString("NationalCode_Must_Be_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا شماره پرونده را وارد کنید.
        /// </summary>
        public static string No_Is_Not_Entered {
            get {
                return ResourceManager.GetString("No_Is_Not_Entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پرونده معتبر نمی باشد..
        /// </summary>
        public static string No_Is_Not_Valid {
            get {
                return ResourceManager.GetString("No_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه پرداخت معتبر نمی باشد..
        /// </summary>
        public static string PBill4Paid_GetPBill4PaidByFishNo_FishNo_Is_Required {
            get {
                return ResourceManager.GetString("PBill4Paid_GetPBill4PaidByFishNo_FishNo_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبضی یافت نشد..
        /// </summary>
        public static string PBill4Paid_GetPBill4PaidByFishNo_PBill4Paid_NotFound {
            get {
                return ResourceManager.GetString("PBill4Paid_GetPBill4PaidByFishNo_PBill4Paid_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت قبض نامعتبر است..
        /// </summary>
        public static string PBill4Paid_GetPBill4PaidByFishNo_PBill4Paid_TheObjectState_Is_Null {
            get {
                return ResourceManager.GetString("PBill4Paid_GetPBill4PaidByFishNo_PBill4Paid_TheObjectState_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست نمی تواند خالی باشد..
        /// </summary>
        public static string PBill4Paid_GetPBill4PaidByFishNo_Request_Is_Required {
            get {
                return ResourceManager.GetString("PBill4Paid_GetPBill4PaidByFishNo_Request_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست ورودی خالی یا نا معتبر میباشد.
        /// </summary>
        public static string PBill4Paid_GetPBill4PaidByFishNo_ThePBill4PaidFishNoContract_Is_Required {
            get {
                return ResourceManager.GetString("PBill4Paid_GetPBill4PaidByFishNo_ThePBill4PaidFishNoContract_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدملی شخص مربوط به قبض معتبر نمی باشد..
        /// </summary>
        public static string PBill4Paid_GetPBill4PaidListByNationalCode_NationalCode_Is_Required {
            get {
                return ResourceManager.GetString("PBill4Paid_GetPBill4PaidListByNationalCode_NationalCode_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبض مربوطه یافت نشد..
        /// </summary>
        public static string PBill4Paid_GetPBill4PaidListByNationalCode_PBill4Paid_NotFound {
            get {
                return ResourceManager.GetString("PBill4Paid_GetPBill4PaidListByNationalCode_PBill4Paid_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست معتبر نمی باشد..
        /// </summary>
        public static string PBill4Paid_GetPBill4PaidListByNationalCode_Request_Is_Required {
            get {
                return ResourceManager.GetString("PBill4Paid_GetPBill4PaidListByNationalCode_Request_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورودی درخواست نمی تواند خالی باشد..
        /// </summary>
        public static string PBill4Paid_GetPBill4PaidListByNationalCode_ThePBill4PaidNationalCodeContract_Is_Required {
            get {
                return ResourceManager.GetString("PBill4Paid_GetPBill4PaidListByNationalCode_ThePBill4PaidNationalCodeContract_Is_R" +
                        "equired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فراخوانی سرویس سداد با خطا مواجه شد..
        /// </summary>
        public static string PBill4Paid_SendPaymentRequestToSadad_CallGetToken_HasError {
            get {
                return ResourceManager.GetString("PBill4Paid_SendPaymentRequestToSadad_CallGetToken_HasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه پرداخت معتبر نمی باشد..
        /// </summary>
        public static string PBill4Paid_SendPaymentRequestToSadad_FishNo_Is_Required {
            get {
                return ResourceManager.GetString("PBill4Paid_SendPaymentRequestToSadad_FishNo_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای برگشتی از سرویس سداد..
        /// </summary>
        public static string PBill4Paid_SendPaymentRequestToSadad_GetToken_HasError {
            get {
                return ResourceManager.GetString("PBill4Paid_SendPaymentRequestToSadad_GetToken_HasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شبای قبض یافت نشد..
        /// </summary>
        public static string PBill4Paid_SendPaymentRequestToSadad_IBAN_NotFound {
            get {
                return ResourceManager.GetString("PBill4Paid_SendPaymentRequestToSadad_IBAN_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شبای قبض معتبر نیست..
        /// </summary>
        public static string PBill4Paid_SendPaymentRequestToSadad_IBAN_NotValid {
            get {
                return ResourceManager.GetString("PBill4Paid_SendPaymentRequestToSadad_IBAN_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبض مورد نظر یافت نشد..
        /// </summary>
        public static string PBill4Paid_SendPaymentRequestToSadad_PBill4Paid_NotFound {
            get {
                return ResourceManager.GetString("PBill4Paid_SendPaymentRequestToSadad_PBill4Paid_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست نمی تواند خالی باشد.
        /// </summary>
        public static string PBill4Paid_SendPaymentRequestToSadad_Request_Is_Required {
            get {
                return ResourceManager.GetString("PBill4Paid_SendPaymentRequestToSadad_Request_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورودی درخواست نمی تواند خالی باشد.
        /// </summary>
        public static string PBill4Paid_SendPaymentRequestToSadad_ThePBill4PaidFishNoContract_Is_Required {
            get {
                return ResourceManager.GetString("PBill4Paid_SendPaymentRequestToSadad_ThePBill4PaidFishNoContract_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع مبلغ قبض معتبر نمی باشد..
        /// </summary>
        public static string PBill4Paid_SendPaymentRequestToSadad_TotalPaidCost_NotFound {
            get {
                return ResourceManager.GetString("PBill4Paid_SendPaymentRequestToSadad_TotalPaidCost_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه واریزی قبض معتبر نمی باشد..
        /// </summary>
        public static string PBill4Paid_SendPaymentRequestToSadad_TreasuryID_NotFound {
            get {
                return ResourceManager.GetString("PBill4Paid_SendPaymentRequestToSadad_TreasuryID_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره قبض بیش از اندازه مجاز می باشد.
        /// </summary>
        public static string PBillStore_BillNumber_IsTooLong {
            get {
                return ResourceManager.GetString("PBillStore_BillNumber_IsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ وارده طولانی یا نامعتبر است.
        /// </summary>
        public static string PBillStore_Date_IsInvalid {
            get {
                return ResourceManager.GetString("PBillStore_Date_IsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره قبض تکراری است و امروز قابل ثبت نیست.
        /// </summary>
        public static string PBillStore_Duplicate_Bill {
            get {
                return ResourceManager.GetString("PBillStore_Duplicate_Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست کالا خالی است!.
        /// </summary>
        public static string PBillStore_NoProductListProvided {
            get {
                return ResourceManager.GetString("PBillStore_NoProductListProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست معتبر نمی باشد..
        /// </summary>
        public static string PBillStore_Request_NotValid {
            get {
                return ResourceManager.GetString("PBillStore_Request_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت و ارسال به مرجع رسیدگی کننده.
        /// </summary>
        public static string PDiscoveryMinuteSate_ConfirmAndSendToUnit {
            get {
                return ResourceManager.GetString("PDiscoveryMinuteSate_ConfirmAndSendToUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تشکیل پرونده شده است..
        /// </summary>
        public static string PDiscoveryMinuteSate_CreateCase {
            get {
                return ResourceManager.GetString("PDiscoveryMinuteSate_CreateCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابطال شده است ..
        /// </summary>
        public static string PDiscoveryMinuteSate_Expired {
            get {
                return ResourceManager.GetString("PDiscoveryMinuteSate_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره یکتای صورتجلسه کشف ارسالی معتبر نمی باشد.
        /// </summary>
        public static string PDiscoveryMinuteSate_No_Is_NotValid {
            get {
                return ResourceManager.GetString("PDiscoveryMinuteSate_No_Is_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورتجلسه كشف / گزارش كشف اسنادي ثبت موقت شده.
        /// </summary>
        public static string PDiscoveryMinuteSate_PrimRegistery {
            get {
                return ResourceManager.GetString("PDiscoveryMinuteSate_PrimRegistery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال شده به شهر دیگر به دلیل اشتباه در ارجاع.
        /// </summary>
        public static string PDiscoveryMinuteSate_ReferToCity {
            get {
                return ResourceManager.GetString("PDiscoveryMinuteSate_ReferToCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارجاع شده به شعبه رسیدگی کننده.
        /// </summary>
        public static string PDiscoveryMinuteSate_ReferToUnit {
            get {
                return ResourceManager.GetString("PDiscoveryMinuteSate_ReferToUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورتجلسه کشف ارسال شده به سامانه قاچاق.
        /// </summary>
        public static string PDiscoveryMinuteSate_SendToSmuggling {
            get {
                return ResourceManager.GetString("PDiscoveryMinuteSate_SendToSmuggling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع شده.
        /// </summary>
        public static string PDiscoveryMinuteSate_Start {
            get {
                return ResourceManager.GetString("PDiscoveryMinuteSate_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد {0} خالی یا نامعتبر می باشد.
        /// </summary>
        public static string PGravamen_Field_IsNullOrInvalid {
            get {
                return ResourceManager.GetString("PGravamen_Field_IsNullOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز فایل ارسالی بیش از حد مجاز است.
        /// </summary>
        public static string PGravamen_FileIsLargerThanAllowedThreshold {
            get {
                return ResourceManager.GetString("PGravamen_FileIsLargerThanAllowedThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی شخص نا معتبر میباشد.
        /// </summary>
        public static string PGravamen_GetPersonPGravamenInfoResult_PersonNationalityCode_Is_Required {
            get {
                return ResourceManager.GetString("PGravamen_GetPersonPGravamenInfoResult_PersonNationalityCode_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی شخص نا معتبر میباشد.
        /// </summary>
        public static string PGravamen_GetPersonPGravamenInfoResult_PersonNationalityCode_Not_Valid {
            get {
                return ResourceManager.GetString("PGravamen_GetPersonPGravamenInfoResult_PersonNationalityCode_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شکوائیه ای برای شخص یافت نشد.
        /// </summary>
        public static string PGravamen_GetPersonPGravamenInfoResult_PGravamens_NotFound {
            get {
                return ResourceManager.GetString("PGravamen_GetPersonPGravamenInfoResult_PGravamens_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست معتبر نمی باشد.
        /// </summary>
        public static string PGravamen_GetPersonPGravamenInfoResult_Request_Is_Required {
            get {
                return ResourceManager.GetString("PGravamen_GetPersonPGravamenInfoResult_Request_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات شخص نا معتبر میباشد.
        /// </summary>
        public static string PGravamen_GetPersonPGravamenInfoResult_TheGetPersonPGravamenInfoCoPGravamen_GetPersonPGravamenInfoResult_TheGetPersonPGravamenInfoContract_Is_Required {
            get {
                return ResourceManager.GetString("PGravamen_GetPersonPGravamenInfoResult_TheGetPersonPGravamenInfoCoPGravamen_GetPe" +
                        "rsonPGravamenInfoResult_TheGetPersonPGravamenInfoContract_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  درخواست ورودی نامعتبر یا خالی می‌باشد.
        /// </summary>
        public static string PGravamen_GetPersonPGravamenStatisticResult_Request_Is_Required {
            get {
                return ResourceManager.GetString("PGravamen_GetPersonPGravamenStatisticResult_Request_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ملی شخص نامعتبر یا خالی می‌باشد.
        /// </summary>
        public static string PGravamen_GetPersonPGravamenStatisticResult_TheNationalityCode_Is_Required {
            get {
                return ResourceManager.GetString("PGravamen_GetPersonPGravamenStatisticResult_TheNationalityCode_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پیگیری معتبر نمی باشد..
        /// </summary>
        public static string PGravamen_GetPGravamenInfo_FollowUpNo_Is_Required {
            get {
                return ResourceManager.GetString("PGravamen_GetPGravamenInfo_FollowUpNo_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شکوائیه مورد نظر یافت نشد..
        /// </summary>
        public static string PGravamen_GetPGravamenInfo_PGravamen_NotFound {
            get {
                return ResourceManager.GetString("PGravamen_GetPGravamenInfo_PGravamen_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست نمی تواند خالی باشد..
        /// </summary>
        public static string PGravamen_GetPGravamenInfo_Request_Is_Required {
            get {
                return ResourceManager.GetString("PGravamen_GetPGravamenInfo_Request_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست ورودی خالی یا نا معتبر میباشد.
        /// </summary>
        public static string PGravamen_GetPGravamenInfo_ThePGravamenContract_Is_Required {
            get {
                return ResourceManager.GetString("PGravamen_GetPGravamenInfo_ThePGravamenContract_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک یا هر دو جایگاه ضروری در شکوائیه، وجود ندارد.
        /// </summary>
        public static string PGravamen_NecessaryPositions_AreNotAvailabe {
            get {
                return ResourceManager.GetString("PGravamen_NecessaryPositions_AreNotAvailabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست فایل های ارسالی خالی است.
        /// </summary>
        public static string PGravamen_NoAttachmentAvailable {
            get {
                return ResourceManager.GetString("PGravamen_NoAttachmentAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ فایلی الصاق نشده است.
        /// </summary>
        public static string PGravamen_NoFileIsAttached {
            get {
                return ResourceManager.GetString("PGravamen_NoFileIsAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} برای شخص متهم ضروری است.
        /// </summary>
        public static string PGravamen_OffendingNecessaryField_IsNullOrInvalid {
            get {
                return ResourceManager.GetString("PGravamen_OffendingNecessaryField_IsNullOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} برای شخص شاکی ضروری است.
        /// </summary>
        public static string PGravamen_PlatiffNecessaryField_IsNullOrInvalid {
            get {
                return ResourceManager.GetString("PGravamen_PlatiffNecessaryField_IsNullOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست ورودی خالی یا نامعتبر است.
        /// </summary>
        public static string PGravamen_Request_IsNullOrCorrupt {
            get {
                return ResourceManager.GetString("PGravamen_Request_IsNullOrCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال مکان جغرافیایی الزامی می‌باشد.
        /// </summary>
        public static string PGravamen_TheGeoLocation_IsRequired {
            get {
                return ResourceManager.GetString("PGravamen_TheGeoLocation_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن همراه را وارد کنید..
        /// </summary>
        public static string PhoneNumber_Is_Not_Entered {
            get {
                return ResourceManager.GetString("PhoneNumber_Is_Not_Entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن همراه معتبر نمی باشد..
        /// </summary>
        public static string PhoneNumber_Is_Not_Valid {
            get {
                return ResourceManager.GetString("PhoneNumber_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پيش نويس.
        /// </summary>
        public static string PInspectionReport_Drafted {
            get {
                return ResourceManager.GetString("PInspectionReport_Drafted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش بازرسي توسط شاكي ثبت شده.
        /// </summary>
        public static string PInspectionReport_Drafted_Old {
            get {
                return ResourceManager.GetString("PInspectionReport_Drafted_Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به واحد اجرای احکام ارجاع شده.
        /// </summary>
        public static string PInspectionReport_Execution {
            get {
                return ResourceManager.GetString("PInspectionReport_Execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت نسخه فیزیکی پرونده قبل از نسخه الکترونیکی.
        /// </summary>
        public static string PInspectionReport_Expired {
            get {
                return ResourceManager.GetString("PInspectionReport_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره مکانیزه گزارش بازرسی ارسالی معتبر نمی باشد.
        /// </summary>
        public static string PInspectionReport_No_Is_NotValid {
            get {
                return ResourceManager.GetString("PInspectionReport_No_Is_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رای صادر شده است..
        /// </summary>
        public static string PInspectionReport_PJudgment {
            get {
                return ResourceManager.GetString("PInspectionReport_PJudgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دريافت شده از سازمان گزارش دهنده.
        /// </summary>
        public static string PInspectionReport_Received_From_SupportOrg {
            get {
                return ResourceManager.GetString("PInspectionReport_Received_From_SupportOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش بازرسي ارجاع شده.
        /// </summary>
        public static string PInspectionReport_Refered_old {
            get {
                return ResourceManager.GetString("PInspectionReport_Refered_old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارجاع شده به شعبه.
        /// </summary>
        public static string PInspectionReport_Referred {
            get {
                return ResourceManager.GetString("PInspectionReport_Referred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارجاع شده به شهرستان.
        /// </summary>
        public static string PInspectionReport_Referred_To_City {
            get {
                return ResourceManager.GetString("PInspectionReport_Referred_To_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع به رسیدگی و تشكيل پرونده شده.
        /// </summary>
        public static string PInspectionReport_RegisterCase {
            get {
                return ResourceManager.GetString("PInspectionReport_RegisterCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت شده جهت تاييد مدير.
        /// </summary>
        public static string PInspectionReport_Registered_to_ManagerConfirm {
            get {
                return ResourceManager.GetString("PInspectionReport_Registered_to_ManagerConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برگشت شده به ثبت كننده جهت اصلاح.
        /// </summary>
        public static string PInspectionReport_Return_to_Registrar {
            get {
                return ResourceManager.GetString("PInspectionReport_Return_to_Registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برگشت شده به شهرستان ارجاع دهنده جهت اصلاح.
        /// </summary>
        public static string PInspectionReport_Returnd_to_Referrer {
            get {
                return ResourceManager.GetString("PInspectionReport_Returnd_to_Referrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برگشت شده به سازمان ارسال کننده.
        /// </summary>
        public static string PInspectionReport_Returnd_To_Sender {
            get {
                return ResourceManager.GetString("PInspectionReport_Returnd_To_Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رای صادر شده است..
        /// </summary>
        public static string PJudgment {
            get {
                return ResourceManager.GetString("PJudgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابلاغ مد نظر یافت نشد.
        /// </summary>
        public static string PNotice_ChangePNoticeViewByUserStatus_PNotice_NotFound {
            get {
                return ResourceManager.GetString("PNotice_ChangePNoticeViewByUserStatus_PNotice_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ابلاغ نامعتبر میباشد.
        /// </summary>
        public static string PNotice_ChangePNoticeViewByUserStatus_PNoticeNo_Is_Required {
            get {
                return ResourceManager.GetString("PNotice_ChangePNoticeViewByUserStatus_PNoticeNo_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست ورودی خالی یا نا معتبر میباشد.
        /// </summary>
        public static string PNotice_ChangePNoticeViewByUserStatus_Request_Is_Required {
            get {
                return ResourceManager.GetString("PNotice_ChangePNoticeViewByUserStatus_Request_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست ورودی خالی یا نا معتبر میباشد.
        /// </summary>
        public static string PNotice_ChangePNoticeViewByUserStatus_ThePNoticeNoInputContract_Is_Required {
            get {
                return ResourceManager.GetString("PNotice_ChangePNoticeViewByUserStatus_ThePNoticeNoInputContract_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن ابلاغیه یافت نشد..
        /// </summary>
        public static string PNotice_ExportPNotice_Description_NotFound {
            get {
                return ResourceManager.GetString("PNotice_ExportPNotice_Description_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ابلاغ را وارد کنید..
        /// </summary>
        public static string PNotice_ExportPNotice_No_Is_Required {
            get {
                return ResourceManager.GetString("PNotice_ExportPNotice_No_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابلاغیه ای یافت نشد..
        /// </summary>
        public static string PNotice_ExportPNotice_NotFound {
            get {
                return ResourceManager.GetString("PNotice_ExportPNotice_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست نمی تواند خالی باشد..
        /// </summary>
        public static string PNotice_ExportPNotice_Request_Is_Required {
            get {
                return ResourceManager.GetString("PNotice_ExportPNotice_Request_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات وارد شده نمی تواند خالی باشد..
        /// </summary>
        public static string PNotice_ExportPNotice_ThePNoticeNoInputContract_Is_Required {
            get {
                return ResourceManager.GetString("PNotice_ExportPNotice_ThePNoticeNoInputContract_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدملی معتبر نمی باشد..
        /// </summary>
        public static string PNotice_GetCountOfUnSeenPNoticeByUser_NationalityCode_Is_Required {
            get {
                return ResourceManager.GetString("PNotice_GetCountOfUnSeenPNoticeByUser_NationalityCode_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابلاغی یافت نشد.
        /// </summary>
        public static string PNotice_GetCountOfUnSeenPNoticeByUser_PNotice_NotFound {
            get {
                return ResourceManager.GetString("PNotice_GetCountOfUnSeenPNoticeByUser_PNotice_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست نمی تواند خالی باشد..
        /// </summary>
        public static string PNotice_GetCountOfUnSeenPNoticeByUser_Request_Is_Required {
            get {
                return ResourceManager.GetString("PNotice_GetCountOfUnSeenPNoticeByUser_Request_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست ورودی خالی یا نا معتبر میباشد.
        /// </summary>
        public static string PNotice_GetCountOfUnSeenPNoticeByUser_ThePNoticePersonContract_Is_Required {
            get {
                return ResourceManager.GetString("PNotice_GetCountOfUnSeenPNoticeByUser_ThePNoticePersonContract_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدملی/شناسه ملی درخواست نمی تواند خالی باشد..
        /// </summary>
        public static string PNotice_InqueryPNoticeList_NationalityCode_Is_Required {
            get {
                return ResourceManager.GetString("PNotice_InqueryPNoticeList_NationalityCode_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابلاغیه ای یافت نشد..
        /// </summary>
        public static string PNotice_InqueryPNoticeList_NotFound {
            get {
                return ResourceManager.GetString("PNotice_InqueryPNoticeList_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست نمی تواند خالی باشد..
        /// </summary>
        public static string PNotice_InqueryPNoticeList_Request_Is_Required {
            get {
                return ResourceManager.GetString("PNotice_InqueryPNoticeList_Request_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات وارد شده نمی تواند خالی باشد..
        /// </summary>
        public static string PNotice_InqueryPNoticeList_ThePNoticePersonContract_Is_Required {
            get {
                return ResourceManager.GetString("PNotice_InqueryPNoticeList_ThePNoticePersonContract_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرتب سازی ویژگی یافت نشد..
        /// </summary>
        public static string PropertyOrderNotFound {
            get {
                return ResourceManager.GetString("PropertyOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در خواست شما معتبر نمی باشد.
        /// </summary>
        public static string Request_Is_Not_Valid {
            get {
                return ResourceManager.GetString("Request_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات وارد شده معتبر نمی باشد..
        /// </summary>
        public static string SabteAhval_Data_Not_Match_Entered_Data {
            get {
                return ResourceManager.GetString("SabteAhval_Data_Not_Match_Entered_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدملی معتبر نمی باشد..
        /// </summary>
        public static string SabteAhval_Not_Validate_NationalCode {
            get {
                return ResourceManager.GetString("SabteAhval_Not_Validate_NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا ثبت احوال.
        /// </summary>
        public static string SabteAhval_Unkhown_Error {
            get {
                return ResourceManager.GetString("SabteAhval_Unkhown_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مجددا {0} ثانیه دیگر تلاش کنید.
        /// </summary>
        public static string Send_Login_Request_After_x_Second {
            get {
                return ResourceManager.GetString("Send_Login_Request_After_x_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه کاربر به کد ملی {0} تکراری است.
        /// </summary>
        public static string SendSmsForChangePhoneNumber_Mobile_Number_is_Repetitive {
            get {
                return ResourceManager.GetString("SendSmsForChangePhoneNumber_Mobile_Number_is_Repetitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر در سامانه ثبت نام نکرده است.
        /// </summary>
        public static string SendSmsForChangePhoneNumber_Not_Find_User {
            get {
                return ResourceManager.GetString("SendSmsForChangePhoneNumber_Not_Find_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست معتبر نمی باشد..
        /// </summary>
        public static string SendSmsForChangePhoneNumber_request_Not_Valid {
            get {
                return ResourceManager.GetString("SendSmsForChangePhoneNumber_request_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن یا کد ملی معتبر نمی‌باشد.
        /// </summary>
        public static string SendSmsForChangePhoneNumber_UserName_or_PhoneNumber_Not_Valid {
            get {
                return ResourceManager.GetString("SendSmsForChangePhoneNumber_UserName_or_PhoneNumber_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت معتبر نمی باشد.
        /// </summary>
        public static string Sex_Is_Not_Valid {
            get {
                return ResourceManager.GetString("Sex_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان استعلام تطابق شماره تلفن و کد ملی وجود به شماره ملی {0} ندارد..
        /// </summary>
        public static string Shahkar_Could_Not_Inquiry {
            get {
                return ResourceManager.GetString("Shahkar_Could_Not_Inquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم تطابق شماره تلفن همراه با کد ملی  به شماره ملی {0}.
        /// </summary>
        public static string Shahkar_NationalCode_PhoneNumber_Is_Not_Match {
            get {
                return ResourceManager.GetString("Shahkar_NationalCode_PhoneNumber_Is_Not_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار شماره تلفن همراه با کد ملی به شماره ملی {0}  نامعتبر است..
        /// </summary>
        public static string Shahkar_NationalCode_PhoneNumber_Is_Not_Valid {
            get {
                return ResourceManager.GetString("Shahkar_NationalCode_PhoneNumber_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا شاهکار.
        /// </summary>
        public static string Shahkar_Unkhown_Error {
            get {
                return ResourceManager.GetString("Shahkar_Unkhown_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما به محدودیت ارسال اس ام اس رسیده اید لطفا مجدد فردا مراجعه کنید..
        /// </summary>
        public static string Sms_Limit_Send {
            get {
                return ResourceManager.GetString("Sms_Limit_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان انتظار ارسال کد به پایان رسیده است. لطفا مجدد اقدام به دریافت کد کنید ..
        /// </summary>
        public static string Sms_Time_Is_Expired {
            get {
                return ResourceManager.GetString("Sms_Time_Is_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد ..
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مکان جغرافیایی گزارش بازرسی نمی تواند خالی باشد.
        /// </summary>
        public static string ThePBBillGeoLocation_Is_Required {
            get {
                return ResourceManager.GetString("ThePBBillGeoLocation_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر وجود دارد..
        /// </summary>
        public static string User_Is_Exist {
            get {
                return ResourceManager.GetString("User_Is_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری و کلمه عبور را وارد کنید.
        /// </summary>
        public static string UserName_Or_PassWord_Is_Not_Entered {
            get {
                return ResourceManager.GetString("UserName_Or_PassWord_Is_Not_Entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با نام کاربری و کلمه عبور ارسالی هیچ دسترسی برای سرویس جاری یافت نشد.
        /// </summary>
        public static string UserName_Or_PassWord_Is_Not_Valid {
            get {
                return ResourceManager.GetString("UserName_Or_PassWord_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما هیچ پرونده ای ندارید..
        /// </summary>
        public static string You_Do_Not_Have_Any_Case {
            get {
                return ResourceManager.GetString("You_Do_Not_Have_Any_Case", resourceCulture);
            }
        }
    }
}
