//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ServiceModel;

namespace SmsMagfa
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Name = "MagfaSoapServer", Namespace = "webservice.magfa.com", ConfigurationName = "SmsMagfa.MagfaSoapServer")]
    public interface MagfaSoapServer
    {

        [System.ServiceModel.OperationContractAttribute(Action = "urn:processDocument", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(customerReturnIncomingFormat))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "messagesAsync")]
        System.Threading.Tasks.Task<SmsMagfa.messagesResult> messagesAsync(int count, string shortNumber);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:processDocument", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(customerReturnIncomingFormat))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "midAsync")]
        System.Threading.Tasks.Task<SmsMagfa.messageIdResult> midAsync(long uid);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:processDocument", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(customerReturnIncomingFormat))]
        System.Threading.Tasks.Task<SmsMagfa.statusesResponse> statusesAsync(SmsMagfa.statuses request);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:processDocument", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(customerReturnIncomingFormat))]
        System.Threading.Tasks.Task<SmsMagfa.sendResponse> sendAsync(SmsMagfa.send request);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:processDocument", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(customerReturnIncomingFormat))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "balanceAsync")]
        System.Threading.Tasks.Task<SmsMagfa.creditResult> balanceAsync();
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("messagesResult", Namespace = "webservice.magfa.com")]
    public partial class messagesResult
    {

        private int statusField;

        private datedCustomerReturnIncomingFormat[] messagesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("status", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messages", IsNullable = true, Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public datedCustomerReturnIncomingFormat[] messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("datedCustomerReturnIncomingFormat", Namespace = "webservice.magfa.com")]
    public partial class datedCustomerReturnIncomingFormat : customerReturnIncomingFormat
    {

        private string dateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("date", IsNullable = true, Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(datedCustomerReturnIncomingFormat))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("customerReturnIncomingFormat", Namespace = "webservice.magfa.com")]
    public partial class customerReturnIncomingFormat
    {

        private string bodyField;

        private string senderNumberField;

        private string recipientNumberField;

        private string errorResultField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("body", IsNullable = true, Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("senderNumber", IsNullable = true, Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string senderNumber
        {
            get
            {
                return this.senderNumberField;
            }
            set
            {
                this.senderNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recipientNumber", IsNullable = true, Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string recipientNumber
        {
            get
            {
                return this.recipientNumberField;
            }
            set
            {
                this.recipientNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errorResult", IsNullable = true, Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string errorResult
        {
            get
            {
                return this.errorResultField;
            }
            set
            {
                this.errorResultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("creditResult", Namespace = "webservice.magfa.com")]
    public partial class creditResult
    {

        private int statusField;

        private decimal balanceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("status", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("balance", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public decimal balance
        {
            get
            {
                return this.balanceField;
            }
            set
            {
                this.balanceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("sendMessage", Namespace = "webservice.magfa.com")]
    public partial class sendMessage
    {

        private string alphabetField;

        private long idField;

        private int partsField;

        private string recipientField;

        private int statusField;

        private double tariffField;

        private long userIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("alphabet", IsNullable = true, Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string alphabet
        {
            get
            {
                return this.alphabetField;
            }
            set
            {
                this.alphabetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parts", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public int parts
        {
            get
            {
                return this.partsField;
            }
            set
            {
                this.partsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recipient", IsNullable = true, Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string recipient
        {
            get
            {
                return this.recipientField;
            }
            set
            {
                this.recipientField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("status", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tariff", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public double tariff
        {
            get
            {
                return this.tariffField;
            }
            set
            {
                this.tariffField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userId", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public long userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("sendResult", Namespace = "webservice.magfa.com")]
    public partial class sendResult
    {

        private int statusField;

        private sendMessage[] messagesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("status", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messages", IsNullable = true, Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public sendMessage[] messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("deliveryStatus", Namespace = "webservice.magfa.com")]
    public partial class deliveryStatus
    {

        private long midField;

        private int statusField;

        private string dateField;

        private string smscField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mid", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public long mid
        {
            get
            {
                return this.midField;
            }
            set
            {
                this.midField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("status", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("date", IsNullable = true, Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("smsc", IsNullable = true, Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string smsc
        {
            get
            {
                return this.smscField;
            }
            set
            {
                this.smscField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("deliveryResult", Namespace = "webservice.magfa.com")]
    public partial class deliveryResult
    {

        private int statusField;

        private deliveryStatus[] dlrsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("status", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dlrs", IsNullable = true, Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public deliveryStatus[] dlrs
        {
            get
            {
                return this.dlrsField;
            }
            set
            {
                this.dlrsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("messageIdResult", Namespace = "webservice.magfa.com")]
    public partial class messageIdResult
    {

        private int statusField;

        private long midField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("status", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mid", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public long mid
        {
            get
            {
                return this.midField;
            }
            set
            {
                this.midField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "statuses", WrapperNamespace = "webservice.magfa.com", IsWrapped = true)]
    [System.Xml.Serialization.XmlRoot(Namespace = "webservice.magfa.com")]
    public partial class statuses
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "webservice.magfa.com", Order = 0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<long>[] mids;

        public statuses()
        {
        }

        public statuses(System.Nullable<long>[] mids)
        {
            this.mids = mids;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "statusesResponse", WrapperNamespace = "webservice.magfa.com", IsWrapped = true)]
    [System.Xml.Serialization.XmlRoot(Namespace = "webservice.magfa.com")]
    public partial class statusesResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "webservice.magfa.com", Order = 0)]
        public SmsMagfa.deliveryResult @return;

        public statusesResponse()
        {
        }

        public statusesResponse(SmsMagfa.deliveryResult @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "send", WrapperNamespace = "webservice.magfa.com", IsWrapped = true)]
    [System.Xml.Serialization.XmlRoot(Namespace = "webservice.magfa.com")]
    public partial class send
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "webservice.magfa.com", Order = 0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("messages", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] messages;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "webservice.magfa.com", Order = 1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("senders", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] senders;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "webservice.magfa.com", Order = 2)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("recipients", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] recipients;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "webservice.magfa.com", Order = 3)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("uids", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<long>[] uids;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "webservice.magfa.com", Order = 4)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("encodings", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int>[] encodings;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "webservice.magfa.com", Order = 5)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("udhs", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] udhs;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "webservice.magfa.com", Order = 6)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("priorities", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int>[] priorities;

        public send()
        {
        }

        public send(string[] messages, string[] senders, string[] recipients, System.Nullable<long>[] uids, System.Nullable<int>[] encodings, string[] udhs, System.Nullable<int>[] priorities)
        {
            this.messages = messages;
            this.senders = senders;
            this.recipients = recipients;
            this.uids = uids;
            this.encodings = encodings;
            this.udhs = udhs;
            this.priorities = priorities;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "sendResponse", WrapperNamespace = "webservice.magfa.com", IsWrapped = true)]
    [System.Xml.Serialization.XmlRoot(Namespace = "webservice.magfa.com")]
    public partial class sendResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "webservice.magfa.com", Order = 0)]
        public SmsMagfa.sendResult @return;

        public sendResponse()
        {
        }

        public sendResponse(SmsMagfa.sendResult @return)
        {
            this.@return = @return;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface MagfaSoapServerChannel : SmsMagfa.MagfaSoapServer, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class MagfaSoapServerClient : System.ServiceModel.ClientBase<SmsMagfa.MagfaSoapServer>, SmsMagfa.MagfaSoapServer
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public MagfaSoapServerClient() :
                base(MagfaSoapServerClient.GetDefaultBinding(), MagfaSoapServerClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MagfaSoapServer.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MagfaSoapServerClient(EndpointConfiguration endpointConfiguration) :
                base(MagfaSoapServerClient.GetBindingForEndpoint(endpointConfiguration), MagfaSoapServerClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MagfaSoapServerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(MagfaSoapServerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MagfaSoapServerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(MagfaSoapServerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MagfaSoapServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public MagfaSoapServerClient(string endpointUrl, TimeSpan timeout, string username, string password) :
                base(MagfaSoapServerClient.GetBindingForEndpoint(timeout), MagfaSoapServerClient.GetEndpointAddress(endpointUrl))
        {
            this.ChannelFactory.Credentials.UserName.UserName = username;
            this.ChannelFactory.Credentials.UserName.Password = password;
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public System.Threading.Tasks.Task<SmsMagfa.messagesResult> messagesAsync(int count, string shortNumber)
        {
            return base.Channel.messagesAsync(count, shortNumber);
        }

        public System.Threading.Tasks.Task<SmsMagfa.messageIdResult> midAsync(long uid)
        {
            return base.Channel.midAsync(uid);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsMagfa.statusesResponse> SmsMagfa.MagfaSoapServer.statusesAsync(SmsMagfa.statuses request)
        {
            return base.Channel.statusesAsync(request);
        }

        public System.Threading.Tasks.Task<SmsMagfa.statusesResponse> statusesAsync(System.Nullable<long>[] mids)
        {
            SmsMagfa.statuses inValue = new SmsMagfa.statuses();
            inValue.mids = mids;
            return ((SmsMagfa.MagfaSoapServer)(this)).statusesAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsMagfa.sendResponse> SmsMagfa.MagfaSoapServer.sendAsync(SmsMagfa.send request)
        {
            return base.Channel.sendAsync(request);
        }

        public System.Threading.Tasks.Task<SmsMagfa.sendResponse> sendAsync(string[] messages, string[] senders, string[] recipients, System.Nullable<long>[] uids, System.Nullable<int>[] encodings, string[] udhs, System.Nullable<int>[] priorities)
        {
            SmsMagfa.send inValue = new SmsMagfa.send();
            inValue.messages = messages;
            inValue.senders = senders;
            inValue.recipients = recipients;
            inValue.uids = uids;
            inValue.encodings = encodings;
            inValue.udhs = udhs;
            inValue.priorities = priorities;
            return ((SmsMagfa.MagfaSoapServer)(this)).sendAsync(inValue);
        }

        public System.Threading.Tasks.Task<SmsMagfa.creditResult> balanceAsync()
        {
            return base.Channel.balanceAsync();
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MagfaSoapServer))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MagfaSoapServer))
            {
                return new System.ServiceModel.EndpointAddress("https://sms.magfa.com/api/soap/sms/v2/server");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MagfaSoapServerClient.GetBindingForEndpoint(EndpointConfiguration.MagfaSoapServer);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MagfaSoapServerClient.GetEndpointAddress(EndpointConfiguration.MagfaSoapServer);
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(TimeSpan timeout)
        {
            var httpsBinding = new BasicHttpsBinding();
            httpsBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Basic;
            httpsBinding.Security.Mode = BasicHttpsSecurityMode.Transport;

            var integerMaxValue = int.MaxValue;
            httpsBinding.MaxBufferSize = integerMaxValue;
            httpsBinding.MaxReceivedMessageSize = integerMaxValue;
            httpsBinding.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            httpsBinding.AllowCookies = true;

            httpsBinding.ReceiveTimeout = timeout;
            httpsBinding.SendTimeout = timeout;
            httpsBinding.OpenTimeout = timeout;
            httpsBinding.CloseTimeout = timeout;

            return httpsBinding;
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(string endpointUrl)
        {
            if (!endpointUrl.StartsWith("https://"))
            {
                throw new UriFormatException("The endpoint URL must start with https://.");
            }
            return new System.ServiceModel.EndpointAddress(endpointUrl);
        }

        public enum EndpointConfiguration
        {

            MagfaSoapServer,
        }
    }
}
